# Generated by Django 2.2.4 on 2019-12-30 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('title', models.TextField(help_text='Title of the movie', max_length=256, verbose_name='Title')),
                ('year', models.CharField(blank=True, help_text='Year of release', max_length=10, null=True, verbose_name='Year')),
                ('rated', models.CharField(blank=True, help_text='PG rating', max_length=50, null=True, verbose_name='Rated')),
                ('released', models.CharField(blank=True, help_text='Date of release', max_length=30, null=True, verbose_name='Released')),
                ('runtime', models.TextField(blank=True, help_text='Length of movie (mins)', null=True, verbose_name='Runtime')),
                ('genre', models.TextField(blank=True, max_length=200, null=True, verbose_name='Genre')),
                ('director', models.TextField(blank=True, max_length=200, null=True, verbose_name='Director')),
                ('writer', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Writer')),
                ('actors', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Actors')),
                ('plot', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Plot')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Language')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('awards', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Awards')),
                ('poster', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Poster')),
                ('metascore', models.CharField(blank=True, max_length=10, null=True, verbose_name='Metascore')),
                ('imdbrating', models.CharField(blank=True, max_length=30, null=True, verbose_name='IMDB Rating')),
                ('imdbvotes', models.CharField(blank=True, max_length=30, null=True, verbose_name='IMDB votes')),
                ('imdbid', models.CharField(blank=True, max_length=50, null=True, verbose_name='IMDB ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('dvd', models.CharField(blank=True, max_length=30, null=True, verbose_name='DVD release date')),
                ('boxoffice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Box Office')),
                ('production', models.CharField(blank=True, max_length=500, null=True, verbose_name='Production')),
                ('website', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Website')),
                ('comments_count', models.PositiveIntegerField(blank=True, default=0, verbose_name='Comments count')),
            ],
            options={
                'ordering': ['-comments_count'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('source', models.CharField(max_length=200, verbose_name='Source')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('content', models.TextField(max_length=2000, verbose_name='Comment content')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Movie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
